export const MAX_AGENT_WORKBOOK_IMPORT_BYTES = 64 * 1024 * 1024

export const MAX_AGENT_WORKBOOK_IMPORT_BASE64_LENGTH = 4 * Math.ceil(MAX_AGENT_WORKBOOK_IMPORT_BYTES / 3)

export const MAX_AGENT_FRAME_PAYLOAD_BYTES = MAX_AGENT_WORKBOOK_IMPORT_BASE64_LENGTH + 64 * 1024

export const MAX_AGENT_FRAME_BYTES = MAX_AGENT_FRAME_PAYLOAD_BYTES + 10
