import type {
  ExcelExpectedValue,
  ExcelFixtureCase,
  ExcelFixtureExpectedOutput,
  ExcelFixtureFamily,
  ExcelFixtureInputCell,
} from './index.js'

const excelFixtureIdPattern = /^[a-z][a-z0-9-]*:[a-z0-9-]+$/

function createExcelFixtureId(family: ExcelFixtureFamily, slug: string): string {
  const normalizedSlug = slug.trim().toLowerCase()
  const id = `${family}:${normalizedSlug}`
  if (!excelFixtureIdPattern.test(id)) {
    throw new Error(`Invalid Excel fixture id: ${id}`)
  }
  return id
}

function numberExpected(value: number): ExcelExpectedValue {
  return { kind: 'number', value }
}

function stringExpected(value: string): ExcelExpectedValue {
  return { kind: 'string', value }
}

function input(address: string, value: ExcelFixtureInputCell['input'], note?: string): ExcelFixtureInputCell {
  return note === undefined ? { address, input: value } : { address, input: value, note }
}

function output(address: string, expected: ExcelFixtureExpectedOutput['expected'], note?: string): ExcelFixtureExpectedOutput {
  return note === undefined ? { address, expected } : { address, expected, note }
}

function fixture(
  family: ExcelFixtureFamily,
  slug: string,
  title: string,
  formula: string,
  inputs: ExcelFixtureInputCell[],
  outputs: ExcelFixtureExpectedOutput[],
  notes?: string,
): ExcelFixtureCase {
  const base = {
    id: createExcelFixtureId(family, slug),
    family,
    title,
    formula,
    inputs,
    outputs,
    sheetName: 'Sheet1',
  }
  return notes === undefined ? base : { ...base, notes }
}

export const canonicalExpansionFixtures: readonly ExcelFixtureCase[] = [
  fixture(
    'logical',
    'switch-does-not-match-boolean-number',
    'SWITCH does not match booleans to numbers',
    '=SWITCH(1,TRUE(),"yes","no")',
    [],
    [output('A1', stringExpected('no'))],
    'Microsoft and Google document SWITCH as a first matching value/case selector; HyperFormula returns the default for this mixed boolean-number case.',
  ),
  fixture(
    'logical',
    'switch-does-not-match-number-boolean',
    'SWITCH does not match numbers to booleans',
    '=SWITCH(TRUE(),1,"number","default")',
    [],
    [output('A1', stringExpected('default'))],
    'HyperFormula and TrueCalc return the default for this mixed boolean-number case.',
  ),
  fixture(
    'logical',
    'switch-does-not-match-numeric-text',
    'SWITCH does not match numeric text to numbers',
    '=SWITCH(12,"12","numeric text","default")',
    [],
    [output('A1', stringExpected('default'))],
    'Microsoft and Google document SWITCH as a first matching value/case selector; HyperFormula returns the default for this mixed numeric-text case.',
  ),
  fixture(
    'logical',
    'switch-does-not-match-text-number',
    'SWITCH does not match text to numbers',
    '=SWITCH("12",12,"number","default")',
    [],
    [output('A1', stringExpected('default'))],
    'HyperFormula and TrueCalc return the default for this mixed numeric-text case.',
  ),
  fixture(
    'text',
    'exact-basic',
    'EXACT case-sensitive text comparison',
    '=EXACT("Alpha","alpha")',
    [],
    [output('A1', { kind: 'boolean', value: false })],
  ),
  fixture('text', 'left-basic', 'LEFT basic prefix extraction', '=LEFT("alpha",3)', [], [output('A1', stringExpected('alp'))]),
  fixture('text', 'right-basic', 'RIGHT basic suffix extraction', '=RIGHT("alpha",2)', [], [output('A1', stringExpected('ha'))]),
  fixture('text', 'mid-basic', 'MID basic substring extraction', '=MID("alphabet",2,3)', [], [output('A1', stringExpected('lph'))]),
  fixture(
    'text',
    'len-counts-surrogate-pair-as-one-character',
    'LEN counts a Unicode surrogate pair as one character',
    '=LEN("😀")',
    [],
    [output('A1', numberExpected(1))],
    'Excel Compatibility Version 2 counts Unicode surrogate pairs as one character for LEN.',
  ),
  fixture(
    'text',
    'mid-extracts-surrogate-pair-as-one-character',
    'MID extracts a Unicode surrogate pair as one character',
    '=MID("x😀y",2,1)',
    [],
    [output('A1', stringExpected('😀'))],
    'Excel Compatibility Version 2 counts Unicode surrogate pairs as one character for MID.',
  ),
  fixture('text', 'trim-basic', 'TRIM removes extra spaces', '=TRIM("  alpha   beta  ")', [], [output('A1', stringExpected('alpha beta'))]),
  fixture('text', 'upper-basic', 'UPPER uppercases text', '=UPPER("Alpha beta")', [], [output('A1', stringExpected('ALPHA BETA'))]),
  fixture('text', 'lower-basic', 'LOWER lowercases text', '=LOWER("Alpha BETA")', [], [output('A1', stringExpected('alpha beta'))]),
  fixture('text', 'find-basic', 'FIND basic case-sensitive search', '=FIND("ph","alphabet")', [], [output('A1', numberExpected(3))]),
  fixture(
    'text',
    'find-counts-surrogate-pair-as-one-character',
    'FIND counts a Unicode surrogate pair as one character',
    '=FIND("y","x😀y")',
    [],
    [output('A1', numberExpected(3))],
    'Excel Compatibility Version 2 counts Unicode surrogate pairs as one character for FIND positions.',
  ),
  fixture(
    'text',
    'search-basic',
    'SEARCH basic case-insensitive search',
    '=SEARCH("PH","alphabet")',
    [],
    [output('A1', numberExpected(3))],
  ),
  fixture(
    'text',
    'search-counts-surrogate-pair-as-one-character',
    'SEARCH counts a Unicode surrogate pair as one character',
    '=SEARCH("Y","x😀y")',
    [],
    [output('A1', numberExpected(3))],
    'Excel Compatibility Version 2 counts Unicode surrogate pairs as one character for SEARCH positions.',
  ),
  fixture(
    'text',
    'replace-counts-surrogate-pair-as-one-character',
    'REPLACE counts a Unicode surrogate pair as one character',
    '=REPLACE("x😀y",2,1,"Q")',
    [],
    [output('A1', stringExpected('xQy'))],
    'Excel Compatibility Version 2 counts Unicode surrogate pairs as one character for REPLACE.',
  ),
  fixture(
    'text',
    'substitute-empty-old-text-returns-original',
    'SUBSTITUTE empty old text returns original text',
    '=SUBSTITUTE("abc","","Z")',
    [],
    [output('A1', stringExpected('abc'))],
    'TrueCalc and xlsx-calc agree that empty old_text leaves the text unchanged.',
  ),
  fixture(
    'text',
    'value-basic',
    'VALUE text-to-number coercion',
    '=VALUE("42")',
    [],
    [output('A1', numberExpected(42))],
    'Canonical literal case now closes through constant folding; dynamic text-input VALUE semantics still route through the JS oracle.',
  ),
  fixture(
    'lookup-reference',
    'xmatch-basic',
    'XMATCH exact match',
    '=XMATCH("pear",A1:A3,0)',
    [input('A1', 'apple'), input('A2', 'pear'), input('A3', 'plum')],
    [output('A4', numberExpected(2))],
  ),
  fixture(
    'lookup-reference',
    'lookup-short-result-vector',
    'LOOKUP accepts a shorter result vector when the matched result slot exists',
    '=LOOKUP(0.6666666666666666,B1:B16,C1:C15)',
    [
      input('B1', 0),
      input('B2', 0.199),
      input('B3', 0.299),
      input('B4', 0.599),
      input('B5', 1.1),
      input('B6', 2.1),
      input('B7', 4.1),
      input('B8', 8.1),
      input('B9', 16.1),
      input('B10', 32.1),
      input('B11', 64.1),
      input('B12', 128.1),
      input('B13', 256.1),
      input('B14', 512.1),
      input('B15', 1024.1),
      input('B16', 2048),
      input('C1', 1),
      input('C2', 2),
      input('C3', 3),
      input('C4', 4),
      input('C5', 5),
      input('C6', 6),
      input('C7', 7),
      input('C8', 8),
      input('C9', 9),
      input('C10', 10),
      input('C11', 11),
      input('C12', 12),
      input('C13', 13),
      input('C14', 14),
      input('C15', 15),
    ],
    [output('A1', numberExpected(4))],
    'XLSX fixture corpus case Biomass-spreadsheet-CEND0313.xlsx stores the same mismatched LOOKUP vector shape with cached result 4 for this threshold slot.',
  ),
  fixture(
    'lookup-reference',
    'hlookup-basic',
    'HLOOKUP exact match across header row',
    '=HLOOKUP("pear",A1:C2,2,FALSE)',
    [input('A1', 'apple'), input('B1', 'pear'), input('C1', 'plum'), input('A2', 10), input('B2', 20), input('C2', 30)],
    [output('D1', numberExpected(20))],
  ),
  fixture(
    'lookup-reference',
    'xlookup-approximate-scalar-vector',
    'XLOOKUP next-smaller scalar vector match',
    '=XLOOKUP(72,G1:G5,H1:H5,,-1)',
    [
      input('G1', 50),
      input('G2', 60),
      input('G3', 70),
      input('G4', 80),
      input('G5', 90),
      input('H1', 500),
      input('H2', 600),
      input('H3', 700),
      input('H4', 800),
      input('H5', 900),
    ],
    [output('A1', numberExpected(700))],
  ),
  fixture(
    'lookup-reference',
    'offset-basic',
    'OFFSET relative reference',
    '=OFFSET(A1,1,1)',
    [input('A1', 10), input('B2', 20)],
    [output('A2', numberExpected(20))],
    'Canonical corpus case; reference-returning semantics are still open.',
  ),
  fixture(
    'lookup-reference',
    'rows-scalar-array',
    'ROWS treats a scalar argument as a one-cell array',
    '=ROWS(1)',
    [],
    [output('A1', numberExpected(1))],
    'Evaluator differential confirms scalar arguments contribute one row; direct error arguments still propagate.',
  ),
  fixture(
    'lookup-reference',
    'address-r1c1-logical-false',
    'ADDRESS uses FALSE for R1C1 reference style',
    '=ADDRESS(2,3,2,FALSE())',
    [],
    [output('A1', stringExpected('R2C[3]'))],
    'Microsoft documents ADDRESS a1 as a logical flag: TRUE or omitted returns A1 style; FALSE returns R1C1 style.',
  ),
  fixture(
    'lookup-reference',
    'address-simple-sheet-unquoted',
    'ADDRESS leaves simple sheet names unquoted',
    '=ADDRESS(1,1,1,TRUE(),"Sheet2")',
    [],
    [output('A1', stringExpected('Sheet2!$A$1'))],
    'Microsoft documents ADDRESS sheet_text example =ADDRESS(1,1,,,"Sheet2") returning Sheet2!$A$1 without quoting the simple sheet name.',
  ),
  fixture(
    'lookup-reference',
    'columns-scalar-array',
    'COLUMNS treats a scalar argument as a one-cell array',
    '=COLUMNS("x")',
    [],
    [output('A1', numberExpected(1))],
    'Evaluator differential confirms scalar arguments contribute one column; direct error arguments still propagate.',
  ),
  fixture(
    'text',
    'value-date-text',
    'VALUE accepts date text formats',
    '=VALUE("1/1/2024")',
    [],
    [output('A1', numberExpected(45292))],
    'Microsoft documents VALUE text as accepting constant number, date, or time formats recognized by Excel.',
  ),
  fixture(
    'text',
    'value-date-time-text',
    'VALUE preserves date and time text serials',
    '=VALUE("1/1/2024 12:00:00")',
    [],
    [output('A1', numberExpected(45292.5))],
    'VALUE accepts date and time formats recognized by Excel; evaluator differential confirms date-time text keeps both the date serial and time fraction.',
  ),
  fixture(
    'text',
    'value-overflow-time-text',
    'VALUE preserves elapsed days for overflow time text',
    '=VALUE("25:00:00")',
    [],
    [output('A1', numberExpected(25 / 24))],
    'Evaluator differential confirms VALUE returns elapsed days for overflow time text rather than only the clock-time fraction.',
  ),
  fixture(
    'date-time',
    'timevalue-overflow-time-text',
    'TIMEVALUE wraps overflow time text to the day fraction',
    '=TIMEVALUE("25:00:00")',
    [],
    [output('A1', numberExpected(1 / 24))],
    'Evaluator differential confirms TIMEVALUE accepts overflow time text and returns the normalized time-of-day fraction.',
  ),
  fixture(
    'logical',
    'if-missing-false-branch',
    'IF with missing false branch returns FALSE',
    '=IF(FALSE(),1)',
    [],
    [output('A1', { kind: 'boolean', value: false })],
    'Microsoft documents value_if_false as optional; evaluator differential confirms a missing false branch returns FALSE, unlike an explicitly omitted comma argument.',
  ),
  fixture(
    'dynamic-array',
    'take-basic',
    'TAKE returns leading rows',
    '=TAKE(A1:A4,2)',
    [input('A1', 1), input('A2', 2), input('A3', 3), input('A4', 4)],
    [output('B1', numberExpected(1)), output('B2', numberExpected(2))],
  ),
  fixture(
    'dynamic-array',
    'drop-basic',
    'DROP removes leading rows',
    '=DROP(A1:A4,2)',
    [input('A1', 1), input('A2', 2), input('A3', 3), input('A4', 4)],
    [output('B1', numberExpected(3)), output('B2', numberExpected(4))],
  ),
  fixture(
    'dynamic-array',
    'choosecols-basic',
    'CHOOSECOLS selects explicit columns',
    '=CHOOSECOLS(A1:C2,1,3)',
    [input('A1', 1), input('B1', 2), input('C1', 3), input('A2', 4), input('B2', 5), input('C2', 6)],
    [output('D1', numberExpected(1)), output('E1', numberExpected(3)), output('D2', numberExpected(4)), output('E2', numberExpected(6))],
  ),
  fixture(
    'dynamic-array',
    'chooserows-basic',
    'CHOOSEROWS selects explicit rows',
    '=CHOOSEROWS(A1:B3,1,3)',
    [input('A1', 1), input('B1', 2), input('A2', 3), input('B2', 4), input('A3', 5), input('B3', 6)],
    [output('D1', numberExpected(1)), output('E1', numberExpected(2)), output('D2', numberExpected(5)), output('E2', numberExpected(6))],
  ),
  fixture(
    'dynamic-array',
    'groupby-basic',
    'GROUPBY aggregates rows into grouped spill output',
    '=GROUPBY(A1:A5,C1:C5,SUM,3,1)',
    [
      input('A1', 'Region'),
      input('A2', 'East'),
      input('A3', 'West'),
      input('A4', 'East'),
      input('A5', 'West'),
      input('C1', 'Sales'),
      input('C2', 10),
      input('C3', 7),
      input('C4', 5),
      input('C5', 4),
    ],
    [
      output('E1', stringExpected('Region')),
      output('F1', stringExpected('Sales')),
      output('E2', stringExpected('East')),
      output('F2', numberExpected(15)),
      output('E3', stringExpected('West')),
      output('F3', numberExpected(11)),
      output('E4', stringExpected('Total')),
      output('F4', numberExpected(26)),
    ],
    'Current production routing stays on the JS-special path while grouped spill semantics remain outside the native kernel.',
  ),
  fixture(
    'dynamic-array',
    'pivotby-basic',
    'PIVOTBY aggregates values into a pivot-style spill matrix',
    '=PIVOTBY(A1:A5,B1:B5,C1:C5,SUM,3,1,0,1)',
    [
      input('A1', 'Region'),
      input('A2', 'East'),
      input('A3', 'West'),
      input('A4', 'East'),
      input('A5', 'West'),
      input('B1', 'Product'),
      input('B2', 'Widget'),
      input('B3', 'Widget'),
      input('B4', 'Gizmo'),
      input('B5', 'Gizmo'),
      input('C1', 'Sales'),
      input('C2', 10),
      input('C3', 7),
      input('C4', 5),
      input('C5', 4),
    ],
    [
      output('H1', stringExpected('Region')),
      output('I1', stringExpected('Widget')),
      output('J1', stringExpected('Gizmo')),
      output('K1', stringExpected('Total')),
      output('H2', stringExpected('East')),
      output('I2', numberExpected(10)),
      output('J2', numberExpected(5)),
      output('K2', numberExpected(15)),
      output('H3', stringExpected('West')),
      output('I3', numberExpected(7)),
      output('J3', numberExpected(4)),
      output('K3', numberExpected(11)),
      output('H4', stringExpected('Total')),
      output('I4', numberExpected(17)),
      output('J4', numberExpected(9)),
      output('K4', numberExpected(26)),
    ],
    'Current production routing stays on the JS-special path while pivot-style grouped spills remain outside the native kernel.',
  ),
  fixture(
    'statistical',
    'sumif-basic',
    'SUMIF with scalar criteria',
    '=SUMIF(A1:A4,">0",B1:B4)',
    [input('A1', 2), input('A2', -1), input('A3', 4), input('A4', 0), input('B1', 10), input('B2', 20), input('B3', 30), input('B4', 40)],
    [output('C1', numberExpected(40))],
  ),
  fixture(
    'statistical',
    'sumifs-basic',
    'SUMIFS with paired criteria ranges',
    '=SUMIFS(C1:C4,A1:A4,">0",B1:B4,"x")',
    [
      input('A1', 2),
      input('A2', -1),
      input('A3', 4),
      input('A4', 7),
      input('B1', 'x'),
      input('B2', 'x'),
      input('B3', 'y'),
      input('B4', 'x'),
      input('C1', 10),
      input('C2', 20),
      input('C3', 30),
      input('C4', 40),
    ],
    [output('D1', numberExpected(50))],
  ),
  fixture(
    'statistical',
    'averageifs-basic',
    'AVERAGEIFS with paired criteria ranges',
    '=AVERAGEIFS(C1:C4,A1:A4,">0",B1:B4,"x")',
    [
      input('A1', 2),
      input('A2', -1),
      input('A3', 4),
      input('A4', 7),
      input('B1', 'x'),
      input('B2', 'x'),
      input('B3', 'y'),
      input('B4', 'x'),
      input('C1', 10),
      input('C2', 20),
      input('C3', 30),
      input('C4', 40),
    ],
    [output('D1', numberExpected(25))],
  ),
  fixture(
    'statistical',
    'countifs-basic',
    'COUNTIFS with paired criteria ranges',
    '=COUNTIFS(A1:A4,">0",B1:B4,"x")',
    [
      input('A1', 2),
      input('A2', -1),
      input('A3', 4),
      input('A4', 7),
      input('B1', 'x'),
      input('B2', 'x'),
      input('B3', 'y'),
      input('B4', 'x'),
    ],
    [output('C1', numberExpected(2))],
  ),
  fixture(
    'math',
    'sumproduct-basic',
    'SUMPRODUCT multiplies and sums aligned arrays',
    '=SUMPRODUCT(A1:A3,B1:B3)',
    [input('A1', 1), input('A2', 2), input('A3', 3), input('B1', 4), input('B2', 5), input('B3', 6)],
    [output('C1', numberExpected(32))],
  ),
  fixture('math', 'int-basic', 'INT rounds toward negative infinity', '=INT(-3.1)', [], [output('A1', numberExpected(-4))]),
  fixture('math', 'int-empty-text-coercion', 'INT empty text coercion', '=INT("")', [], [output('A1', numberExpected(0))]),
  fixture('math', 'roundup-basic', 'ROUNDUP rounds away from zero', '=ROUNDUP(12.341,2)', [], [output('A1', numberExpected(12.35))]),
  fixture('math', 'rounddown-basic', 'ROUNDDOWN rounds toward zero', '=ROUNDDOWN(12.349,2)', [], [output('A1', numberExpected(12.34))]),
  fixture(
    'math',
    'floor-zero-number-zero-significance',
    'FLOOR returns zero when number and significance are both zero',
    '=FLOOR(0,0)',
    [],
    [output('A1', numberExpected(0))],
    'HyperFormula, TrueCalc, and xlsx-calc all return zero; OpenFormula specifies zero if either FLOOR parameter is zero.',
  ),
  fixture(
    'math',
    'ceiling-zero-number-zero-significance',
    'CEILING returns zero when number and significance are both zero',
    '=CEILING(0,0)',
    [],
    [output('A1', numberExpected(0))],
    'HyperFormula and TrueCalc both return zero; OpenFormula specifies zero if either CEILING parameter is zero.',
  ),
  fixture(
    'date-time',
    'now-volatile',
    'NOW volatile timestamp capture',
    '=NOW()',
    [],
    [output('A1', numberExpected(46100.65659722222))],
    'Oracle output captured for the canonical corpus plan; runtime normalization is still open.',
  ),
  fixture(
    'date-time',
    'date-direct-numeric-text-coercion',
    'DATE coerces direct numeric text arguments',
    '=DATE("2024","1","2")',
    [],
    [output('A1', numberExpected(45293))],
    'HyperFormula and TrueCalc both return serial 45293 for direct numeric text arguments.',
  ),
  fixture(
    'date-time',
    'time-basic',
    'TIME constructs a fractional day serial',
    '=TIME(12,30,0)',
    [],
    [output('A1', numberExpected(0.5208333333333334))],
  ),
  fixture(
    'date-time',
    'time-direct-numeric-text-coercion',
    'TIME coerces direct numeric text arguments',
    '=TIME("1","2","3")',
    [],
    [output('A1', numberExpected(3723 / 86400))],
    'HyperFormula and TrueCalc both return the 01:02:03 day fraction for direct numeric text arguments.',
  ),
  fixture(
    'date-time',
    'time-direct-empty-text-coercion',
    'TIME coerces direct empty text to zero',
    '=TIME("",0,0)',
    [],
    [output('A1', numberExpected(0))],
    'HyperFormula, TrueCalc, and xlsx-calc all return zero for an empty text hour argument.',
  ),
  fixture(
    'date-time',
    'hour-basic',
    'HOUR extracts the hour component',
    '=HOUR(A1)',
    [input('A1', 0.5208333333333334)],
    [output('A2', numberExpected(12))],
  ),
  fixture(
    'date-time',
    'minute-basic',
    'MINUTE extracts the minute component',
    '=MINUTE(A1)',
    [input('A1', 0.5208333333333334)],
    [output('A2', numberExpected(30))],
  ),
  fixture(
    'date-time',
    'second-basic',
    'SECOND extracts the second component',
    '=SECOND(A1)',
    [input('A1', 0.5208449074074074)],
    [output('A2', numberExpected(1))],
  ),
  fixture(
    'date-time',
    'weekday-basic',
    'WEEKDAY returns the default weekday number',
    '=WEEKDAY(DATE(2026,3,15))',
    [],
    [output('A1', numberExpected(1))],
  ),
  fixture(
    'date-time',
    'weekday-1900-leap-bug',
    'WEEKDAY preserves Excel 1900 leap-year compatibility',
    '=WEEKDAY(A1)',
    [input('A1', 1)],
    [output('A2', numberExpected(1))],
    'Microsoft documents that Excel intentionally preserves incorrect WEEKDAY results before March 1, 1900 for serial-date compatibility.',
  ),
  fixture(
    'text',
    'text-weekday-1900-leap-bug',
    'TEXT preserves Excel 1900 weekday-name compatibility',
    '=TEXT(A1,"dddd")',
    [input('A1', 1)],
    [output('A2', stringExpected('Sunday'))],
    'Tracks TEXT weekday names through the same Excel 1900-system compatibility rule as WEEKDAY.',
  ),
  fixture(
    'dynamic-array',
    'sort-basic',
    'SORT reorders a vertical range',
    '=SORT(A1:A4)',
    [input('A1', 3), input('A2', 1), input('A3', 4), input('A4', 2)],
    [output('B1', numberExpected(1)), output('B2', numberExpected(2)), output('B3', numberExpected(3)), output('B4', numberExpected(4))],
  ),
  fixture(
    'dynamic-array',
    'sortby-basic',
    'SORTBY orders values by companion keys',
    '=SORTBY(A1:A3,B1:B3)',
    [input('A1', 'pear'), input('A2', 'apple'), input('A3', 'plum'), input('B1', 2), input('B2', 1), input('B3', 3)],
    [output('C1', stringExpected('apple')), output('C2', stringExpected('pear')), output('C3', stringExpected('plum'))],
  ),
  fixture(
    'dynamic-array',
    'tocol-basic',
    'TOCOL flattens a matrix by rows by default',
    '=TOCOL(A1:B2)',
    [input('A1', 1), input('B1', 2), input('A2', 3), input('B2', 4)],
    [output('C1', numberExpected(1)), output('C2', numberExpected(2)), output('C3', numberExpected(3)), output('C4', numberExpected(4))],
  ),
  fixture(
    'dynamic-array',
    'torow-basic',
    'TOROW flattens a matrix by rows',
    '=TOROW(A1:B2)',
    [input('A1', 1), input('B1', 2), input('A2', 3), input('B2', 4)],
    [output('C1', numberExpected(1)), output('D1', numberExpected(2)), output('E1', numberExpected(3)), output('F1', numberExpected(4))],
  ),
  fixture(
    'dynamic-array',
    'wraprows-basic',
    'WRAPROWS wraps a vector into rows',
    '=WRAPROWS(A1:A4,2)',
    [input('A1', 1), input('A2', 2), input('A3', 3), input('A4', 4)],
    [output('B1', numberExpected(1)), output('C1', numberExpected(2)), output('B2', numberExpected(3)), output('C2', numberExpected(4))],
  ),
  fixture(
    'dynamic-array',
    'wrapcols-basic',
    'WRAPCOLS wraps a vector into columns',
    '=WRAPCOLS(A1:A4,2)',
    [input('A1', 1), input('A2', 2), input('A3', 3), input('A4', 4)],
    [output('B1', numberExpected(1)), output('B2', numberExpected(2)), output('C1', numberExpected(3)), output('C2', numberExpected(4))],
  ),
  {
    ...fixture(
      'names',
      'defined-name-range',
      'Defined-name range reference',
      '=SUM(MyRange)',
      [input('A1', 10), input('A2', 12), input('A3', 15)],
      [output('A4', numberExpected(37))],
      'Requires workbook-level name metadata in the oracle workbook.',
    ),
    definedNames: [{ name: 'MyRange', value: '=A1:A3' }],
  },
  fixture(
    'lambda',
    'byrow-basic',
    'BYROW applies a lambda to each row',
    '=BYROW(A1:B2,LAMBDA(r,SUM(r)))',
    [input('A1', 1), input('B1', 2), input('A2', 3), input('B2', 4)],
    [output('C1', numberExpected(3)), output('C2', numberExpected(7))],
  ),
]
