import { agentNotAFitBoundaries, mcpPromptNames } from './agent-discovery-constants.ts'
import { buildEvaluatorDoors, buildProofContract, compactProofContractJsonArrays } from './agent-discovery-evaluator-doors.ts'
import { formatJsonForRepo } from './generated-json-format.ts'

export type BuildAgentJsonManifestInput = {
  readonly siteRoot: string
  readonly repositoryUrl: string
  readonly skillDiscoveryRoot: string
  readonly skillManifestUrl: string
  readonly skillName: string
  readonly workpaperPackageSpec: string
  readonly remoteMcpEndpoint: string
  readonly remoteMcpAliasEndpoint: string
  readonly remoteMcpServerCard: string
  readonly mcpbReleaseAssetUrl: string
  readonly mcpbReleaseChecksumUrl: string
}

export function buildAgentJsonManifest(input: BuildAgentJsonManifestInput): string {
  const {
    mcpbReleaseAssetUrl,
    mcpbReleaseChecksumUrl,
    remoteMcpAliasEndpoint,
    remoteMcpEndpoint,
    remoteMcpServerCard,
    repositoryUrl,
    siteRoot,
    skillDiscoveryRoot,
    skillManifestUrl,
    skillName,
    workpaperPackageSpec,
  } = input
  const openHandsMcpAddCommand = `openhands mcp add bilig-workpaper --transport stdio npm -- exec --yes --package ${workpaperPackageSpec} -- bilig-workpaper-mcp --workpaper ./.bilig/pricing.workpaper.json --init-demo-workpaper --writable`
  const openCodeMcpCommand = `npm exec --yes --package ${workpaperPackageSpec} -- bilig-workpaper-mcp --workpaper ./.bilig/pricing.workpaper.json --init-demo-workpaper --writable`
  const json = JSON.stringify(
    {
      schema_version: 'agent-json-0.1.0',
      name: 'bilig',
      title: 'Bilig WorkPaper formula readback',
      description:
        'WorkPaper formula readback for Node.js services and MCP tools: edit cells, recalculate, verify outputs, and persist JSON without UI automation.',
      keywords: [
        'WorkPaper formula readback',
        'MCP WorkPaper tools',
        'tool-host workbook automation',
        'headless workbook runtime',
        'JSON WorkPaper persistence',
        '@bilig/workpaper',
      ],
      tags: [
        'workpaper-formula-readback',
        'mcp-workpaper-tools',
        'tool-host-workbook-automation',
        'headless-workpaper',
        'json-workpaper-persistence',
      ],
      url: `${siteRoot}/`,
      repository: repositoryUrl,
      license: 'MIT',
      contact: `${repositoryUrl}/discussions/new?category=general`,
      llms_txt: `${siteRoot}/llms.txt`,
      llms_full: `${siteRoot}/llms-full.txt`,
      llms_install: `${siteRoot}/llms-install.html`,
      llms_install_source: `${repositoryUrl}/blob/main/llms-install.md`,
      well_known_llms_txt: `${siteRoot}/.well-known/llms.txt`,
      well_known_llms_full: `${siteRoot}/.well-known/llms-full.txt`,
      agent_start: `${siteRoot}/agent-start.txt`,
      well_known_agent_start: `${siteRoot}/.well-known/agent-start.txt`,
      skill_file: skillManifestUrl,
      agent_instructions: `${siteRoot}/AGENTS.md`,
      claude_code_instructions: `${repositoryUrl}/blob/main/CLAUDE.md`,
      adoption_kit: `${siteRoot}/agent-adoption-kit.html`,
      skills: [
        {
          name: skillName,
          url: skillManifestUrl,
          index_url: `${siteRoot}/.well-known/agent-skills/index.json`,
          description:
            'Use @bilig/workpaper WorkPaper state, MCP tools, and formula-clinic reports instead of spreadsheet UI automation when a tool host needs formula readback.',
        },
      ],
      evaluator_doors: buildEvaluatorDoors({ repositoryUrl, siteRoot, workpaperPackageSpec }),
      mcp: {
        server_name: 'io.github.proompteng/bilig-workpaper',
        server_card: `${siteRoot}/.well-known/mcp/server-card.json`,
        remote_server_card: remoteMcpServerCard,
        manifest: `${siteRoot}/.well-known/mcp.json`,
        registry_search: 'https://registry.modelcontextprotocol.io/v0.1/servers?search=io.github.proompteng%2Fbilig-workpaper',
        remote_endpoint: remoteMcpEndpoint,
        remote_alias_endpoint: remoteMcpAliasEndpoint,
        remote_transport: {
          type: 'streamable-http',
          protocol_version: '2025-11-25',
          stateless: true,
          authentication_required: false,
        },
        command: 'npm',
        args: [
          'exec',
          '--package',
          workpaperPackageSpec,
          '--',
          'bilig-workpaper-mcp',
          '--workpaper',
          './pricing.workpaper.json',
          '--init-demo-workpaper',
          '--writable',
        ],
        xlsx_import_args: ['exec', '--package', workpaperPackageSpec, '--', 'bilig-workpaper-mcp', '--from-xlsx', './pricing.xlsx'],
        tools: [
          'list_sheets',
          'read_range',
          'read_cell',
          'set_cell_contents',
          'set_cell_contents_and_readback',
          'get_cell_display_value',
          'export_workpaper_document',
          'validate_formula',
        ],
        xlsx_import_tools: ['analyze_workbook_risk'],
        resources: [
          'bilig://workpaper/manifest',
          'bilig://workpaper/agent-handoff',
          'bilig://workpaper/sheets',
          'bilig://workpaper/current-document',
        ],
        prompts: ['edit_and_verify_workpaper', 'debug_workpaper_formula'],
      },
      capabilities: [
        {
          name: 'agent-start',
          type: 'plain-text-entrypoint',
          url: `${siteRoot}/agent-start.txt`,
          well_known_url: `${siteRoot}/.well-known/agent-start.txt`,
          decision_command: `npm exec --yes --package ${workpaperPackageSpec} -- bilig-agent-start --json`,
          challenge_command: `npm exec --yes --package ${workpaperPackageSpec} -- bilig-evaluate --door agent-mcp --json`,
        },
        {
          name: 'agent-adoption-kit',
          type: 'docs-entrypoint',
          docs: `${siteRoot}/agent-adoption-kit.html`,
          skill_install: `npx --yes skills@latest add ${skillDiscoveryRoot} --list`,
          challenge_command: `npm exec --yes --package ${workpaperPackageSpec} -- bilig-evaluate --door agent-mcp --json`,
        },
        {
          name: 'workbook-runtime-intent-api',
          type: 'npm-library',
          package: '@bilig/workbook',
          runtime: 'Node.js >=22',
          install: 'npm install @bilig/workbook',
          docs: `${siteRoot}/workbook-runtime-intent-api.html`,
          source: `${repositoryUrl}/tree/main/examples/workbook-agent-model`,
        },
        {
          name: 'workpaper-formula-runtime',
          type: 'npm-library',
          package: '@bilig/workpaper',
          runtime: 'Node.js >=22',
          install: 'npm install @bilig/workpaper',
          docs: `${siteRoot}/try-bilig-headless-in-node.html`,
        },
        {
          name: 'workbook-compatibility-risk-report',
          type: 'local-cli-evaluator',
          package: '@bilig/xlsx-formula-recalc',
          command: 'npm exec --yes --package @bilig/xlsx-formula-recalc@latest -- bilig-evaluate --door workbook-compatibility --json',
          docs: `${siteRoot}/workbook-compatibility-report.html`,
          source: `${repositoryUrl}/blob/main/docs/workbook-compatibility-report.md`,
          expected_result:
            'bilig-evaluator.v1 JSON with workbook risk reasons, unsupported functions, external links, VBA payloads, pivots, volatile functions, stored formula result counts, no compatibility score, and verified true',
          boundary:
            'Diagnoses workbook risks before service or tool-host use; does not certify Excel compatibility, execute macros, refresh pivots or external data, or assign a compatibility percentage.',
        },
        {
          name: 'agent-xlsx-risk-preflight',
          type: 'mcp-stdio-transcript',
          package: '@bilig/workpaper',
          command: 'pnpm --dir examples/headless-workpaper run agent:mcp-xlsx-risk-preflight',
          docs: `${siteRoot}/agent-xlsx-risk-preflight.html`,
          source: `${repositoryUrl}/blob/main/examples/headless-workpaper/mcp-xlsx-risk-preflight.ts`,
          expected_result:
            'bilig-agent-xlsx-risk-preflight.v1 JSON with analyze_workbook_risk, Inputs!B3, Summary!B3, 60000 -> 96000, exported WorkPaper JSON, restoredReadbackMatchesAfter, excelParity not_proven, and verified true',
          boundary:
            'Local MCP preflight for a real XLSX before edits; risk diagnostics do not certify Excel compatibility or prove desktop Excel UI behavior.',
        },
        {
          name: 'file-backed-workpaper-mcp',
          type: 'mcp-stdio-server',
          docs: `${siteRoot}/mcp-workpaper-tool-server.html`,
          server_card: `${siteRoot}/.well-known/mcp/server-card.json`,
          challenge_command: `npm exec --package ${workpaperPackageSpec} -- bilig-mcp-challenge`,
          xlsx_import_command: `npm exec --package ${workpaperPackageSpec} -- bilig-workpaper-mcp --from-xlsx ./pricing.xlsx`,
          xlsx_import_tool: 'analyze_workbook_risk',
          boundary:
            'The XLSX import tool is local and fixed to the --from-xlsx source file; it reports workbook risk indicators and does not certify Excel compatibility. Without --workpaper --writable, edits stay in memory.',
        },
        {
          name: 'repo-local-agent-instructions',
          type: 'project-agent-instructions',
          claude_code: `${repositoryUrl}/blob/main/CLAUDE.md`,
          codex: `${repositoryUrl}/blob/main/AGENTS.md`,
          aider_conventions: `${repositoryUrl}/blob/main/CONVENTIONS.md`,
          aider_config: `${repositoryUrl}/blob/main/.aider.conf.yml`,
          aider_docs: `${siteRoot}/aider-workpaper-conventions.html`,
          claude_code_skill: `${repositoryUrl}/blob/main/.claude/skills/bilig-workpaper/SKILL.md`,
          claude_code_command: `${repositoryUrl}/blob/main/.claude/commands/bilig-workpaper-proof.md`,
          openhands_skill: `${repositoryUrl}/blob/main/.agents/skills/bilig-workpaper/SKILL.md`,
          opencode_agent: `${repositoryUrl}/blob/main/.opencode/agents/bilig-workpaper.md`,
          kiro_steering: `${repositoryUrl}/blob/main/.kiro/steering/bilig-workpaper.md`,
          trae_rule: `${repositoryUrl}/blob/main/.trae/rules/bilig-workpaper.md`,
          zed_skill: `${repositoryUrl}/blob/main/.agents/skills/bilig-workpaper/SKILL.md`,
          docs: `${siteRoot}/agent-rule-chooser.html`,
          challenge_command: `npm exec --yes --package ${workpaperPackageSpec} -- bilig-evaluate --door agent-mcp --json`,
        },
        {
          name: 'repo-local-mcp-configs',
          type: 'project-mcp-configs',
          claude_code: `${repositoryUrl}/blob/main/.mcp.json`,
          cursor: `${repositoryUrl}/blob/main/.cursor/mcp.json`,
          kiro: `${repositoryUrl}/blob/main/.kiro/settings/mcp.json`,
          junie: `${repositoryUrl}/blob/main/.junie/mcp/mcp.json`,
          trae: `${repositoryUrl}/blob/main/.trae/mcp.json`,
          zed: `${repositoryUrl}/blob/main/.zed/settings.json`,
          opencode: `${repositoryUrl}/blob/main/opencode.jsonc`,
          vscode: `${repositoryUrl}/blob/main/.vscode/mcp.json`,
          reusable: `${repositoryUrl}/blob/main/mcp/bilig-workpaper.mcp.json`,
          docs: `${siteRoot}/mcp-client-setup.html`,
          workpaper_state_path: './.bilig/pricing.workpaper.json',
        },
        {
          name: 'gemini-cli-workpaper-extension',
          type: 'gemini-cli-extension',
          install: repositoryUrl,
          install_command: `gemini extensions install ${repositoryUrl} --ref main`,
          manifest: `${repositoryUrl}/blob/main/gemini-extension.json`,
          context: `${repositoryUrl}/blob/main/gemini-workpaper-context.md`,
          docs: `${siteRoot}/gemini-cli-workpaper-extension.html`,
        },
        {
          name: 'claude-desktop-mcpb',
          type: 'mcpb-desktop-extension',
          download_url: mcpbReleaseAssetUrl,
          checksum_url: mcpbReleaseChecksumUrl,
          docs: `${siteRoot}/claude-desktop-mcpb-workpaper.html`,
        },
        {
          name: 'remote-workpaper-mcp-demo',
          type: 'mcp-streamable-http-server',
          endpoint: remoteMcpEndpoint,
          alias_endpoint: remoteMcpAliasEndpoint,
          server_card: remoteMcpServerCard,
          protocol_version: '2025-11-25',
          authentication_required: false,
          docs: `${siteRoot}/mcp-workpaper-tool-server.html#remote-stateless-endpoint`,
        },
        {
          name: 'openai-agents-sdk-hosted-workpaper-mcp',
          type: 'typescript-agent-mcp-smoke-test',
          framework: 'OpenAI Agents SDK',
          transport: 'streamable-http',
          endpoint: remoteMcpEndpoint,
          command: 'pnpm --dir examples/headless-workpaper run agent:openai-agents-sdk-hosted-mcp',
          docs: `${siteRoot}/openai-agents-sdk-workpaper-tool.html`,
          source: `${repositoryUrl}/blob/main/examples/headless-workpaper/openai-agents-sdk-hosted-mcp-smoke.ts`,
        },
        {
          name: 'openai-responses-workpaper-tool-calls',
          type: 'typescript-function-calling-dispatcher',
          framework: 'OpenAI Responses API',
          api_shape: 'function_call -> function_call_output',
          command: 'pnpm --dir examples/headless-workpaper run agent:openai-responses',
          docs: `${siteRoot}/openai-responses-workpaper-tool-call.html`,
          source: `${repositoryUrl}/blob/main/examples/headless-workpaper/openai-responses-tool-wrapper.ts`,
        },
        {
          name: 'ai-sdk-generate-text-workpaper-tool',
          type: 'typescript-agent-tool-smoke-test',
          framework: 'Vercel AI SDK',
          package: 'ai',
          adapter: '@bilig/workpaper/ai-sdk',
          api_shape: 'generateText -> tool -> execute',
          command: 'pnpm --dir examples/headless-workpaper run agent:ai-sdk-generate-text',
          docs: `${siteRoot}/vercel-ai-sdk-langchain-spreadsheet-tool.html`,
          source: `${repositoryUrl}/blob/main/examples/headless-workpaper/ai-sdk-generate-text-tool-smoke.ts`,
        },
        {
          name: 'ai-sdk-stream-text-workpaper-tool',
          type: 'typescript-agent-tool-smoke-test',
          framework: 'Vercel AI SDK',
          package: 'ai',
          adapter: '@bilig/workpaper/ai-sdk',
          api_shape: 'streamText -> tool -> execute',
          command: 'pnpm --dir examples/headless-workpaper run agent:ai-sdk-stream-text',
          docs: `${siteRoot}/vercel-ai-sdk-langchain-spreadsheet-tool.html`,
          source: `${repositoryUrl}/blob/main/examples/headless-workpaper/ai-sdk-stream-text-tool-smoke.ts`,
        },
        {
          name: 'browser-use-workpaper-formula-tool',
          type: 'python-browser-agent-tool-guide',
          framework: 'Browser Use',
          command: `npm exec --yes --package ${workpaperPackageSpec} -- bilig-evaluate --door agent-mcp --json`,
          docs: `${siteRoot}/browser-use-workpaper-formula-tool.html`,
          source: `${repositoryUrl}/blob/main/docs/browser-use-workpaper-formula-tool.md`,
          upstream_pr: 'https://github.com/browser-use/browser-use/pull/4909',
        },
        {
          name: 'chatgpt-apps-workpaper-mcp',
          type: 'chatgpt-developer-mode-remote-mcp-app',
          framework: 'ChatGPT Apps',
          transport: 'streamable-http',
          endpoint: remoteMcpEndpoint,
          authentication_required: false,
          docs: `${siteRoot}/chatgpt-apps-workpaper-mcp.html`,
          server_card: remoteMcpServerCard,
          proof_command: `npm exec --yes --package ${workpaperPackageSpec} -- bilig-evaluate --door agent-mcp --json`,
        },
        {
          name: 'fastmcp-workpaper-client',
          type: 'python-mcp-client-smoke-test',
          endpoint: remoteMcpEndpoint,
          client: 'FastMCP',
          docs: `${siteRoot}/fastmcp-workpaper-client.html`,
          source: `${repositoryUrl}/tree/main/examples/fastmcp-workpaper-client`,
        },
        {
          name: 'agno-workpaper-mcp',
          type: 'python-agent-mcp-smoke-test',
          framework: 'Agno',
          command:
            'uv run --python 3.12 --with agno --with mcp --with openai python examples/agno-workpaper-mcp/agno_workpaper_mcp.py --output .tmp/agno-workpaper-proof.json',
          docs: `${siteRoot}/agno-workpaper-mcp.html`,
          source: `${repositoryUrl}/tree/main/examples/agno-workpaper-mcp`,
        },
        {
          name: 'pydantic-ai-workpaper-mcp',
          type: 'python-agent-mcp-smoke-test',
          framework: 'Pydantic AI',
          command:
            'uv run --python 3.12 --with pydantic-ai --with mcp --with fastmcp python examples/pydantic-ai-workpaper-mcp/pydantic_ai_workpaper_mcp.py --output .tmp/pydantic-ai-workpaper-proof.json',
          docs: `${siteRoot}/pydantic-ai-workpaper-mcp.html`,
          source: `${repositoryUrl}/tree/main/examples/pydantic-ai-workpaper-mcp`,
        },
        {
          name: 'google-adk-workpaper-mcp',
          type: 'python-agent-mcp-smoke-test',
          framework: 'Google Agent Development Kit',
          command:
            'uv run --python 3.12 --with google-adk --with mcp python examples/google-adk-workpaper-mcp/google_adk_workpaper_mcp.py --output .tmp/google-adk-workpaper-proof.json',
          docs: `${siteRoot}/google-adk-workpaper-mcp.html`,
          source: `${repositoryUrl}/tree/main/examples/google-adk-workpaper-mcp`,
        },
        {
          name: 'microsoft-agent-framework-workpaper-mcp',
          type: 'python-dotnet-agent-mcp-recipe',
          framework: 'Microsoft Agent Framework',
          command: 'python examples/microsoft-agent-framework-workpaper-mcp/scripts/check-microsoft-agent-framework-recipe.py',
          docs: `${siteRoot}/microsoft-agent-framework-workpaper-mcp.html`,
          source: `${repositoryUrl}/tree/main/examples/microsoft-agent-framework-workpaper-mcp`,
        },
        {
          name: 'openhands-workpaper-mcp',
          type: 'coding-agent-mcp-setup',
          framework: 'OpenHands',
          command: openHandsMcpAddCommand,
          config_path: '~/.openhands/mcp.json',
          skill_path: `${repositoryUrl}/blob/main/.agents/skills/bilig-workpaper/SKILL.md`,
          docs: `${siteRoot}/openhands-workpaper-mcp.html`,
          source: `${repositoryUrl}/blob/main/docs/openhands-workpaper-mcp.md`,
        },
        {
          name: 'trae-workpaper-mcp',
          type: 'coding-agent-mcp-setup',
          framework: 'Trae',
          command: openCodeMcpCommand,
          config_path: `${repositoryUrl}/blob/main/.trae/mcp.json`,
          rule_path: `${repositoryUrl}/blob/main/.trae/rules/bilig-workpaper.md`,
          docs: `${siteRoot}/trae-workpaper-mcp.html`,
          source: `${repositoryUrl}/blob/main/docs/trae-workpaper-mcp.md`,
        },
        {
          name: 'qodo-workpaper-mcp',
          type: 'coding-agent-mcp-setup',
          framework: 'Qodo IDE',
          command: openCodeMcpCommand,
          config_shape: 'mcpServers',
          docs: `${siteRoot}/qodo-workpaper-mcp.html`,
          source: `${repositoryUrl}/blob/main/docs/qodo-workpaper-mcp.md`,
          boundary:
            'Qodo IDE Agentic Tools can use the copy-paste local MCP JSON; this repo does not claim a Qodo-specific project config file.',
        },
        {
          name: 'opencode-workpaper-mcp',
          type: 'coding-agent-mcp-setup',
          framework: 'OpenCode',
          command: openCodeMcpCommand,
          config_path: `${repositoryUrl}/blob/main/opencode.jsonc`,
          agent_path: `${repositoryUrl}/blob/main/.opencode/agents/bilig-workpaper.md`,
          docs: `${siteRoot}/opencode-workpaper-mcp.html`,
          source: `${repositoryUrl}/blob/main/docs/opencode-workpaper-mcp.md`,
        },
        {
          name: 'goose-workpaper-mcp',
          type: 'coding-agent-mcp-recipe',
          framework: 'Goose',
          command: 'python examples/goose-workpaper-mcp/scripts/check-goose-recipe.py',
          recipe_path: `${repositoryUrl}/blob/main/examples/goose-workpaper-mcp/recipe.yaml`,
          docs: `${siteRoot}/goose-workpaper-mcp.html`,
          source: `${repositoryUrl}/tree/main/examples/goose-workpaper-mcp`,
        },
        {
          name: 'mastra-workpaper-tool',
          type: 'typescript-agent-tool-smoke-test',
          framework: 'Mastra',
          api_shape: 'createTool -> execute -> WorkPaper readback',
          command: 'pnpm --dir examples/mastra-workpaper-tool run smoke',
          docs: `${siteRoot}/mastra-workpaper-spreadsheet-tool.html`,
          source: `${repositoryUrl}/tree/main/examples/mastra-workpaper-tool`,
        },
        {
          name: 'semantic-kernel-workpaper-mcp',
          type: 'python-agent-mcp-smoke-test',
          framework: 'Microsoft Semantic Kernel',
          command:
            "uv run --python 3.12 --with 'semantic-kernel[mcp]' python examples/semantic-kernel-workpaper-mcp/semantic_kernel_workpaper_mcp.py --output .tmp/semantic-kernel-workpaper-proof.json",
          docs: `${siteRoot}/semantic-kernel-workpaper-mcp.html`,
          source: `${repositoryUrl}/tree/main/examples/semantic-kernel-workpaper-mcp`,
        },
        {
          name: 'smolagents-workpaper-tool',
          type: 'python-agent-tool-smoke-test',
          framework: 'smolagents',
          command: 'uv run --python 3.12 --with smolagents python examples/smolagents-workpaper-tool/smolagents_workpaper_tool.py',
          docs: `${siteRoot}/smolagents-workpaper-tool.html`,
          source: `${repositoryUrl}/tree/main/examples/smolagents-workpaper-tool`,
        },
        {
          name: 'huggingface-workpaper-space-template',
          type: 'gradio-mcp-space-template',
          framework: 'Hugging Face Spaces',
          command:
            "cd examples/huggingface-workpaper-space && npm install --omit=dev --package-lock=false && uv run --python 3.12 --with 'gradio[mcp]>=6.0,<7' python app.py --check",
          docs: `${siteRoot}/huggingface-workpaper-space.html`,
          source: `${repositoryUrl}/tree/main/examples/huggingface-workpaper-space`,
        },
        {
          name: 'inngest-workpaper-step',
          type: 'durable-workflow-step-smoke-test',
          framework: 'Inngest',
          command: 'cd examples/inngest-workpaper-step && pnpm install --ignore-workspace --lockfile=false && pnpm run smoke',
          docs: `${siteRoot}/inngest-workpaper-step.html`,
          source: `${repositoryUrl}/tree/main/examples/inngest-workpaper-step`,
        },
        {
          name: 'airbyte-workpaper-validation',
          type: 'post-sync-validation-smoke-test',
          framework: 'Airbyte',
          command: 'cd examples/airbyte-workpaper-validation && pnpm install --ignore-workspace --lockfile=false && pnpm run smoke',
          docs: `${siteRoot}/airbyte-workpaper-validation.html`,
          source: `${repositoryUrl}/tree/main/examples/airbyte-workpaper-validation`,
        },
        {
          name: 'meltano-workpaper-utility',
          type: 'elt-utility-smoke-test',
          framework: 'Meltano',
          command: 'cd examples/meltano-workpaper-utility && pnpm install --ignore-workspace --lockfile=false && pnpm run smoke',
          docs: `${siteRoot}/meltano-workpaper-utility.html`,
          source: `${repositoryUrl}/tree/main/examples/meltano-workpaper-utility`,
        },
        {
          name: 'formula-clinic',
          type: 'local-cli',
          command: `npm exec --package ${workpaperPackageSpec} -- bilig-formula-clinic ./reduced.xlsx --cells "Summary!B7,Inputs!B2"`,
          docs: `${siteRoot}/formula-bug-clinic.html`,
        },
      ],
      proof_contract: buildProofContract(),
      verification_contract: [
        'read the relevant range before editing',
        'write the target input or formula cell',
        'read the dependent calculated output after recalculation',
        'export or serialize the WorkPaper document',
        'restore or reimport when a file boundary matters',
        'return editedCell, before, after, afterRestore, persistedDocumentBytes, verified, and limitations',
      ],
      boundaries: {
        good_fit: [
          'pricing, quote approval, budget, payout, import-validation, and forecast logic',
          'agent tools that need deterministic cell addresses and formula readback',
          'service-owned workbook state that can persist as JSON',
        ],
        not_a_fit: agentNotAFitBoundaries,
      },
      public_entrypoints: [
        `${siteRoot}/`,
        `${siteRoot}/llms.txt`,
        `${siteRoot}/llms-full.txt`,
        `${siteRoot}/llms-install.html`,
        `${repositoryUrl}/blob/main/llms-install.md`,
        `${siteRoot}/.well-known/llms.txt`,
        `${siteRoot}/.well-known/llms-full.txt`,
        `${siteRoot}/agent-start.txt`,
        `${siteRoot}/.well-known/agent-start.txt`,
        `${repositoryUrl}/blob/main/CLAUDE.md`,
        `${siteRoot}/why-use-bilig.html`,
        `${siteRoot}/workbook-compatibility-report.html`,
        `${repositoryUrl}/blob/main/docs/workbook-compatibility-report.md`,
        `${siteRoot}/workbook-compatibility-report-transcript.html`,
        `${siteRoot}/workbook-compatibility-report.json`,
        `${siteRoot}/agent-xlsx-risk-preflight.html`,
        `${repositoryUrl}/blob/main/examples/headless-workpaper/mcp-xlsx-risk-preflight.ts`,
        `${siteRoot}/eval-xlsx-recalc.html`,
        `${siteRoot}/agent-adoption-kit.html`,
        `${siteRoot}/headless-workpaper-agent-handbook.html`,
        `${repositoryUrl}/blob/main/.mcp.json`,
        `${repositoryUrl}/blob/main/.cursor/mcp.json`,
        `${repositoryUrl}/blob/main/.kiro/settings/mcp.json`,
        `${repositoryUrl}/blob/main/.kiro/steering/bilig-workpaper.md`,
        `${repositoryUrl}/blob/main/.junie/mcp/mcp.json`,
        `${repositoryUrl}/blob/main/.trae/mcp.json`,
        `${repositoryUrl}/blob/main/.trae/rules/bilig-workpaper.md`,
        `${repositoryUrl}/blob/main/.zed/settings.json`,
        `${repositoryUrl}/blob/main/opencode.jsonc`,
        `${repositoryUrl}/blob/main/mcp/bilig-workpaper.mcp.json`,
        `${siteRoot}/agent-workbook-challenge.html`,
        `${siteRoot}/mcp-workpaper-tool-server.html`,
        `${siteRoot}/open-webui-workpaper-mcp.html`,
        `${siteRoot}/open-multi-agent-workpaper-mcp.html`,
        `${siteRoot}/lobehub-workpaper-mcp.html`,
        `${siteRoot}/anythingllm-workpaper-mcp.html`,
        `${siteRoot}/sim-workpaper-mcp.html`,
        `${siteRoot}/fastmcp-workpaper-client.html`,
        `${siteRoot}/agno-workpaper-mcp.html`,
        `${siteRoot}/pydantic-ai-workpaper-mcp.html`,
        `${siteRoot}/google-adk-workpaper-mcp.html`,
        `${siteRoot}/microsoft-agent-framework-workpaper-mcp.html`,
        `${siteRoot}/openhands-workpaper-mcp.html`,
        `${repositoryUrl}/blob/main/docs/openhands-workpaper-mcp.md`,
        `${repositoryUrl}/blob/main/.agents/skills/bilig-workpaper/SKILL.md`,
        `${siteRoot}/trae-workpaper-mcp.html`,
        `${repositoryUrl}/blob/main/docs/trae-workpaper-mcp.md`,
        `${siteRoot}/qodo-workpaper-mcp.html`,
        `${repositoryUrl}/blob/main/docs/qodo-workpaper-mcp.md`,
        `${siteRoot}/opencode-workpaper-mcp.html`,
        `${repositoryUrl}/blob/main/docs/opencode-workpaper-mcp.md`,
        `${repositoryUrl}/blob/main/.opencode/agents/bilig-workpaper.md`,
        `${siteRoot}/goose-workpaper-mcp.html`,
        `${repositoryUrl}/tree/main/examples/goose-workpaper-mcp`,
        `${siteRoot}/smolagents-workpaper-tool.html`,
        `${siteRoot}/huggingface-workpaper-space.html`,
        remoteMcpEndpoint,
        remoteMcpServerCard,
        `${siteRoot}/agent-workpaper-tool-calling-recipe.html`,
        `${siteRoot}/agent-framework-workbook-tools.html`,
        `${siteRoot}/workbook-runtime-intent-api.html`,
        `${siteRoot}/workbook-agent-intent-api.html`,
        `${siteRoot}/openai-agents-sdk-workpaper-tool.html`,
        `${siteRoot}/openai-responses-workpaper-tool-call.html`,
        `${siteRoot}/browser-use-workpaper-formula-tool.html`,
        `${siteRoot}/chatgpt-apps-workpaper-mcp.html`,
        `${siteRoot}/langgraph-workpaper-toolnode-spreadsheet.html`,
        `${siteRoot}/mastra-workpaper-spreadsheet-tool.html`,
        `${siteRoot}/llamaindex-workpaper-spreadsheet-tool.html`,
        `${siteRoot}/crewai-workpaper-spreadsheet-tool.html`,
        `${siteRoot}/cloudflare-agents-workpaper-spreadsheet-tool.html`,
        `${siteRoot}/semantic-kernel-workpaper-mcp.html`,
        `${siteRoot}/gemini-cli-workpaper-extension.html`,
        `${siteRoot}/node-framework-workpaper-adapters.html`,
        `${siteRoot}/n8n-workpaper-formula-readback.html`,
        `${siteRoot}/dify-workpaper-formula-readback.html`,
        `${siteRoot}/flowise-workpaper-formula-readback.html`,
        `${siteRoot}/pipedream-workpaper-formula-readback.html`,
        `${siteRoot}/triggerdev-workpaper-task.html`,
        `${siteRoot}/inngest-workpaper-step.html`,
        `${siteRoot}/airbyte-workpaper-validation.html`,
        `${siteRoot}/meltano-workpaper-utility.html`,
        `${siteRoot}/temporal-workpaper-activity.html`,
        `${siteRoot}/airflow-workpaper-dag.html`,
        `${siteRoot}/dagster-workpaper-asset.html`,
        `${siteRoot}/kestra-workpaper-flow.html`,
        `${siteRoot}/prefect-workpaper-flow.html`,
        `${siteRoot}/npm-provenance-package-trust.html`,
      ],
    },
    null,
    2,
  )
  const compactPersistedBytesAlias = compactProofContractJsonArrays(json, compactStringArrayProperty)
  const compactPrompts = compactStringArrayProperty(compactPersistedBytesAlias, 'prompts', mcpPromptNames, '    ')
  return formatJsonForRepo(compactStringArrayProperty(compactPrompts, 'not_a_fit', agentNotAFitBoundaries, '    '))
}

function compactStringArrayProperty(json: string, propertyName: string, values: readonly string[], indent: string): string {
  const expanded = `${indent}"${propertyName}": [\n${values.map((value) => `${indent}  ${JSON.stringify(value)}`).join(',\n')}\n${indent}]`
  const compact = `${indent}"${propertyName}": [${values.map((value) => JSON.stringify(value)).join(', ')}]`
  return json.replace(expanded, compact)
}
