export function communityLaunchPackRequiredLinks(): readonly string[] {
  return [
    'This file is a current execution trail for legitimate Bilig discovery work.',
    'not contain canned posts, canned comments,\nor outreach scripts.',
    'https://github.com/proompteng/bilig',
    'https://www.npmjs.com/package/@bilig/workpaper',
    'https://proompteng.github.io/bilig/',
    'internal/growth/community-growth-snapshot.md',
    'https://proompteng.github.io/bilig/formula-workbooks-node-services-agent-tools.html',
    'https://proompteng.github.io/bilig/eval-workpaper-service.html',
    'https://proompteng.github.io/bilig/eval-agent-mcp.html',
    'https://proompteng.github.io/bilig/where-bilig-is-not-excel-compatible-yet.html',
    'https://github.com/proompteng/bilig/discussions/157',
    'https://github.com/proompteng/bilig/discussions/213',
    'https://github.com/proompteng/bilig/discussions/230',
    'https://github.com/proompteng/bilig/discussions/335',
    'https://github.com/proompteng/bilig/discussions/340',
    'https://github.com/proompteng/bilig/discussions/382',
    'https://glama.ai/mcp/servers/proompteng/bilig',
    'https://mcprepository.com/proompteng/bilig',
    'https://proompteng.github.io/bilig/mcp-spreadsheet-server-directory.html',
    'https://github.com/krzysztofspilka/JSpreadsheets/pull/50',
    'https://github.com/statico/jsgrids/pull/94',
    'https://github.com/zhangming1978/js-spreadsheet-benchmark/issues/1',
    'https://github.com/chenz24/openawesome/issues/2#issuecomment-4467648527',
    'https://github.com/tolkonepiu/best-of-mcp-servers/pull/192',
    'https://github.com/MunGell/awesome-for-beginners/pull/2012',
    'https://github.com/ever-works/awesome-mcp-servers-data/pull/4',
    'https://github.com/jmstfv/mcpserve/pull/19',
    'https://github.com/MCPFind/mcp-find/pull/37',
    'https://github.com/mctrinh/awesome-mcp-servers/pull/46',
    'https://www.libhunt.com/topic/headless-spreadsheet',
    'Do not buy stars, trade stars, automate follows',
    'Do not paste canned launch comments.',
    'Do not post the same copy across communities.',
    '`100` legitimate GitHub stars',
  ] as const
}

export const llmsExternalSurfaceLinks = [
  'https://github.com/krzysztofspilka/JSpreadsheets/pull/50',
  'https://github.com/statico/jsgrids/pull/94',
  'https://github.com/zhangming1978/js-spreadsheet-benchmark/issues/1',
  'https://github.com/chenz24/openawesome/issues/2#issuecomment-4467648527',
  'https://github.com/tolkonepiu/best-of-mcp-servers/pull/192',
  'https://github.com/MunGell/awesome-for-beginners/pull/2012',
  'https://github.com/ever-works/awesome-mcp-servers-data/pull/4',
  'https://github.com/jmstfv/mcpserve/pull/19',
  'https://github.com/MCPFind/mcp-find/pull/37',
  'https://github.com/mctrinh/awesome-mcp-servers/pull/46',
  'https://mcprepository.com/proompteng/bilig',
  'https://www.libhunt.com/topic/headless-spreadsheet',
] as const
